"""Type stubs for the compiled extension module.

Constructor and query inputs are intentionally broad: a constructor accepts any iterable of
geometry-likes (coordinate sequences, GeoJSON mappings, or ``__geo_interface__`` objects) or
a single collection object; a query accepts any point-like.
"""

from typing import Any

__version__: str

class GeodeticError(ValueError): ...

class Point:
    @property
    def x(self) -> float: ...
    @property
    def y(self) -> float: ...
    @property
    def coordinates(self) -> tuple[float, float]: ...
    @property
    def __geo_interface__(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...

class LineString:
    @property
    def coordinates(self) -> list[tuple[float, float]]: ...
    @property
    def __geo_interface__(self) -> dict[str, Any]: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...

class Polygon:
    @property
    def exterior(self) -> list[tuple[float, float]]: ...
    @property
    def interiors(self) -> list[list[tuple[float, float]]]: ...
    @property
    def __geo_interface__(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...

class GeodeticPointTree:
    def __init__(self, data: Any) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Point: ...
    def geometry(self, index: int) -> Point: ...
    def geometries(self) -> list[Point]: ...
    def nearest(self, query: Any) -> int | None: ...
    def nearest_with_distance(self, query: Any) -> tuple[int, float] | None: ...
    def within_distance(
        self, query: Any, radius_metres: float, return_distance: bool = False
    ) -> list[int] | list[tuple[int, float]]: ...
    def in_rectangle(self, lower: Any, upper: Any) -> list[int]: ...
    def nearest_wgs84(self, query: Any) -> int | None: ...
    def nearest_with_distance_wgs84(self, query: Any) -> tuple[int, float] | None: ...
    def within_distance_wgs84(
        self, query: Any, radius_metres: float, return_distance: bool = False
    ) -> list[int] | list[tuple[int, float]]: ...

class GeodeticLineStringTree:
    def __init__(self, data: Any) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> LineString: ...
    def geometry(self, index: int) -> LineString: ...
    def geometries(self) -> list[LineString]: ...
    def nearest(self, query: Any) -> int | None: ...
    def nearest_with_distance(self, query: Any) -> tuple[int, float] | None: ...
    def within_distance(
        self, query: Any, radius_metres: float, return_distance: bool = False
    ) -> list[int] | list[tuple[int, float]]: ...

class GeodeticPolygonTree:
    def __init__(self, data: Any) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Polygon: ...
    def geometry(self, index: int) -> Polygon: ...
    def geometries(self) -> list[Polygon]: ...
    def nearest(self, query: Any) -> int | None: ...
    def nearest_with_distance(self, query: Any) -> tuple[int, float] | None: ...
    def within_distance(
        self, query: Any, radius_metres: float, return_distance: bool = False
    ) -> list[int] | list[tuple[int, float]]: ...
